apiVersion: v1
kind: Service
metadata:
  name: lz-node-application
  namespace: uat
  labels:
    app: lz-node-application
    name: lz-node-application
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: lz-node-application
    name: lz-node-application
